services:
  - type: web
    name: video-extractor
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.render
    dockerRegistryImageUrl: ""
    envVars:
      - key: NODE_ENV
        value: production
